### ISSUE TITLE
Flickering 

### ISSUE THREAD

**Issue by bastuijnman** [pkmn-world/pkmn-world#14]
## Description

At approximately the following location:
Lat: `52.6298960`
Long: `4.7472470`

The map is rendered but flickers quite heavily.

## Reproduce steps
Open the app in said location and observe the problem

## Possible reasons
It might have something to do with colliders reacting with eachother.

**Comment by thesbros** [comment]
It also happens at other locations. However it doesn't seem to be 100% reproducible, sometimes it flickers and sometimes when you restart it doesn't.

**Comment by bastuijnman** [comment]
Bug was fixed in #15
